---
- name: apply configuration for ztp on oob mgmt
  hosts: oob
  roles:
    - ztp
  tags: [ oob, ztp ]

- name: apply common configuration to all cumulus
  hosts: cumulus
  roles:
    - cumulus
  tags: [ cumulus, spine, leaf ]

- name: apply common configuration to all ubuntu
  hosts: ubuntu
  roles:
    - ubuntu
  tags: [ ubuntu ]
