---
- name: apply common configuration to all cumulus
  hosts: cumulus
  roles:
    - cumulus

- name: apply common configuration to all ubuntu
  hosts: ubuntu
  roles:
    - ubuntu

- name: setup bond between hw spine switches and downlink to leaf
  hosts: hw-spine
  roles:
    - hw_spine_bond
