---
- name: apply configuration for ztp on oob mgmt
  hosts: oob
  roles:
    - ztp
  tags: [ oob, ztp ]

- name: apply common configuration to all cumulus
  hosts: cumulus
  roles:
    - cumulus
  tags: [ cumulus, spine, leaf ]

- name: apply common configuration to all ubuntu
  hosts: ubuntu
  roles:
    - ubuntu
  tags: [ ubuntu ]

- name: setup bond between hw spine switches and downlink to leaf
  hosts: hw-spine
  roles:
    - hw_spine_bond
    - hw_spine_downlink
  tags: [ cumulus, spine ]

- name: setup uplink to leaf
  hosts: hw-leaf
  roles:
    - hw_leaf_uplink
  tags: [ cumulus, leaf ]
