---
- name: apply common configuration to all nodes
  hosts: all
  roles:
    - common

- name: apply common configuration to all cumulus
  hosts: cumulus
  roles:
    - cumulus

- name: apply common configuration to all ubuntu
  hosts: ubuntu
  roles:
    - ubuntu
