---
- name: apply common configuration to all cumulus
  hosts: cumulus
  roles:
    - cumulus

- name: apply common configuration to all ubuntu
  hosts: ubuntu
  roles:
    - ubuntu

- name: setup bond between hw spine switches
  hosts:
    - hw-core-sw[1:2]
  roles:
    - hw_spine_bond
