---
- name: activate interface for mlag
  ansible.builtin.shell: "nv set interface swp49-50 description spine-isl"
  notify: config apply

- name: peerlink for inter-chassis bond aka inter-switch link
  ansible.builtin.shell: "nv set interface peerlink bond member swp49-50"
  notify: config apply
 
- name: mlag mac-address inter-chassis bond 
  ansible.builtin.shell: "nv set mlag mac-address 44:38:39:FF:02:00"
  notify: config apply

- name: mlag peer-ip inter-chassis bond 
  ansible.builtin.shell: "nv set mlag peer-ip linklocal"
  notify: config apply  
