---
- name: activate interface for mlag
  ansible.builtin.shell: "nv set interface swp49-50 description spine-mlag"

- name: apply config
  ansible.builtin.shell: "nv config apply -y"

# - name: bond1
  # ansible.builtin.shell: "nv set interface bond1 bond member swp49-50"

# - name: bond1
  # ansible.builtin.shell: "nv set interface bond1 description bond1-hw-spine"

# - name: bond1
  # ansible.builtin.shell: "nv set interface bond1 bond mlag id 21"

# - name: bond1
  # ansible.builtin.shell: "nv set interface bond1 bridge domain br_default"

# - name: bond1
  # ansible.builtin.shell: "nv set interface peerlink bond member swp49-50"
 
# - name: bond1
  # ansible.builtin.shell: "nv set mlag mac-address 44:38:39:BE:EF:AA"

# - name: bond1
  # ansible.builtin.shell: "nv set mlag peer-ip linklocal"

# - name: bond1
  # ansible.builtin.shell: "nv set mlag backup {{ bond1_mlag_backup }}"

# - name: apply config
  # ansible.builtin.shell: "nv config apply -y"
