---
- name: Configuring Netplan
  ansible.builtin.template:
    src: etc/netplan/eth1.yaml.j2
    dest: /etc/netplan/eth1.yaml
    mode: '0644'
  become: true
  notify: netplan apply
 
- name: Install traceroute
 apt:
   name: traceroute
   state: present
 become: yes
