---
- name: Configuring Netplan
  ansible.builtin.template:
    src: etc/netplan/eth1.yaml.j2
    dest: /etc/netplan/50-eth1.yaml
    mode: '0600'
  become: true
  notify: netplan apply
  when: eth1 is undefined

- name: Install traceroute
  ansible.builtin.apt:
    name: traceroute
    state: present
  become: yes
