#!/bin/bash
set -u

VLAN_OS=1
VLAN_HW=101

function set_bridge(){
  nv set bridge domain br_default vlan 101,102
  nv set bridge domain br_default untagged 1
  nv config apply
}

function firstboot(){
  echo "date: $(date)" > /tmp/.firstboot
  echo 'cumulus_role_version: 0.1' >> /tmp/.firstboot
}

function set_hostname(){
  nv set system hostname "$1"
  nv config apply -y
}

function license(){
  echo -n '' >> /root/cumulus.lic
  cl-license -i /root/cumulus.lic
  systemctl restart switchd.service
}

function set_eth0_ip(){
  nv unset interface eth0 ip address dhcp
  nv set interface eth0 ip ipv6 enable off
  nv set interface eth0 ip address "$1"
  nv config apply -y
}

function modify_user_cumulus(){
  passwd -x 99999 cumulus
  echo '' | chpasswd
}

function create_user_smc(){
  nv set system aaa user smc role nvue-admin
  nv set system aaa user smc full-name "Smart Management Center"
  nv config apply -y
}

function ssh_user_smc(){
  [ -d /home/smc/.ssh ] || mkdir /home/smc/.ssh
  chown smc /home/smc/.ssh
  chgrp smc /home/smc/.ssh
  chmod 700 /home/smc/.ssh
cat << EOF > /home/smc/.ssh/authorized_keys
EOF
}

function set_service_dns(){
  nv set service dns mgmt server "$1"
  nv config apply -y
}

function set_service_ntp(){
  nv unset service ntp mgmt server
  nv set service ntp mgmt server "$1"
  nv config apply -y
}

function set_service_syslog(){
  nv set service syslog mgmt server "$1"
  nv config apply -y
}

function set_spine_peerlink(){
  nv set bridge domain br_default stp priority 8192  # set spine as root bridge for stp
  nv set interface "$1" description spine-isl  # inter-switch link
  nv set interface peerlink bond member "$1"  # create peerlink
  nv set mlag mac-address 44:38:39:FF:02:00  # mlag mac-address for the inter-chassis bond
  nv set mlag backup "$2"
  nv set mlag peer-ip linklocal
  nv config apply -y
}

function set_spine_downlink(){
  nv set interface "$1" description downlink-to-leaf  # description port
  nv set interface "bond${2}" bond member "$1"  # create bond for downlink
  nv set interface "bond${2}" description downlink-to-leaf  # description bond
  nv set interface "bond${2}" bond mlag id "$2"  # mlag id
  nv set interface "bond${2}" bridge domain br_default  # add downlink bond to bridge
  nv config apply -y
}

function set_leaf_uplink(){
  nv set interface "$1" description uplink-to-spine  # description port
  nv set interface "bond${2}" bond member "$1"  # create bond for uplink
  nv set interface "bond${2}" description uplink-to-spine  # description bond
  nv set interface "bond${2}" bond mlag id "$2"  # mlag id
  nv set interface "bond${2}" bridge domain br_default  # add uplink bond to bridge
  nv config apply -y
}

function set_leaf_downlink(){
  nv set interface "$1" description downlink-from-leaf  # description port
  nv set interface "bond${2}" bond member "$1"  # create bond for downlink
  nv set interface "bond${2}" description downlink-from-leaf  # description bond
  nv set interface "bond${2}" bond mlag id "$2"  # mlag id
  if [[ ${3+x} ]]; then
    nv set interface "bond$2" bridge domain br_default access "$3"
  else
    nv set interface "bond$2" bridge domain br_default
  fi
  nv config apply -y
}

function access_ports(){
  function set_interface(){
    nv set interface "$1" description "$2"
    if [[ ${3+x} ]]; then
      nv set interface "$1" bridge domain br_default access "$3"
    else
      nv set interface "$1" bridge domain br_default
    fi
  }
  case ${my_hostname} in
    eth-spine-1 )
      set_interface 'swp20' 'ubuntu-master-1'
      set_interface 'swp7' 'ubuntu-os-1' "${VLAN_OS}"
      nv config apply -y
      ;;
    eth-leaf-1 )
      set_interface 'swp7' 'ubuntu-hw-1' "${VLAN_HW}"
      nv config apply -y
      ;;
  esac

}

function main(){

  firstboot
  #license
  #modify_user_cumulus
  #create_user_smc
  #ssh_user_smc
  set_bridge
  
  my_hostname=$(hostname -s)
  case ${my_hostname} in
  
    eth-spine-1 )
      set_spine_peerlink 'swp49-50' '192.168.200.3'
      set_spine_downlink 'swp3' '11'
      set_spine_downlink 'swp4' '12'
      ;;

    eth-spine-2 )
      set_spine_peerlink 'swp49-50' '192.168.200.2'
      set_spine_downlink 'swp3' '11'
      set_spine_downlink 'swp4' '12'
      ;;
    eth-leaf-1 )
      set_leaf_uplink 'swp49-50' '11'
      ;;
    eth-leaf-2 )
      set_leaf_uplink 'swp49-50' '12'
      set_leaf_downlink 'swp7-8' '21' "${VLAN_OS}"
      ;;
    *)
      echo 'Unknown switch' >&2
      exit 1
      ;; 
  esac

  access_ports ${my_hostname}

  #set_hostname "$my_hostname"
  #set_eth0_ip "$my_cidr"
  #set_service_dns "$my_dns_ip"
  #set_service_ntp "$my_ntp_ip"
  #set_service_syslog "$my_syslog_ip"

}

main "$@"

exit
#CUMULUS-AUTOPROVISIONING
