---
#- name: ztp over dhcp
#  ansible.builtin.lineinfile:
#    path: /etc/dhcp/dhcpd.conf
#    insertafter: '  option default-url = "http://192.168.200.1/onie-installer";'
#    line: '  option cumulus-provision-url "http://192.168.200.1/cumulus-ztp";'
#    backup: true
#  become: true

- name: ztp script
  ansible.builtin.copy:
    src: files/cumulus-ztp
    dest: /var/www/html/cumulus-ztp
    owner: root
    group: root
    mode: '0644'
  become: true
