---

- name: bond1
  ansible.builtin.shell: "nv set interface swp1"
  notify: config apply

- name: bond1
  ansible.builtin.shell: "nv set interface bond1 bond member swp1"
  notify: config apply

- name: bond1
  ansible.builtin.shell: "nv set interface bond1 description bond-on-swp1"
  notify: config apply

- name: bond1
  ansible.builtin.shell: "nv set interface bond1 bond mlag id 1"
  notify: config apply

- name: bond1
  ansible.builtin.shell: "nv set interface bond1 bridge domain br_default"
  notify: config apply

